import { PDFDocument, type PDFFont, StandardFonts, rgb } from "pdf-lib";

export interface Drug {
  name: string;
  dosage: string;
  frequency: string;
  duration: string;
}

export async function buildPrescriptionPDF(opts: {
  refId: string;
  date: string;
  providerName: string;
  providerCredentials: string;
  providerSpecialty: string;
  patientName: string;
  diagnosis: string;
  treatment: string;
  followUp: string;
  drugs: Drug[];
}): Promise<Uint8Array> {
  const doc = await PDFDocument.create();
  const page = doc.addPage([595.28, 841.89]);
  const { width, height } = page.getSize();

  const regular = await doc.embedFont(StandardFonts.Helvetica);
  const bold    = await doc.embedFont(StandardFonts.HelveticaBold);

  const black  = rgb(0.05, 0.05, 0.05);
  const gray   = rgb(0.45, 0.45, 0.45);
  const teal   = rgb(0.05, 0.45, 0.45);
  const border = rgb(0.85, 0.85, 0.85);

  let y = height - 48;
  const L = 50;
  const R = width - 50;
  const W = R - L;

  function line(yPos: number) {
    page.drawLine({ start: { x: L, y: yPos }, end: { x: R, y: yPos }, thickness: 0.5, color: border });
  }

  function text(s: string, x: number, yPos: number, size: number, font = regular, color = black) {
    page.drawText(s, { x, y: yPos, size, font, color });
  }

  page.drawRectangle({ x: L, y: y - 4, width: W, height: 36, color: teal });
  text("STREETDOCMD", L + 10, y + 10, 16, bold, rgb(1, 1, 1));
  text("Medical Prescription", L + 10, y - 2, 9, regular, rgb(0.85, 1, 1));
  y -= 52;

  text(`Date: ${opts.date}`, L, y, 9, regular, gray);
  text(`Ref: #${opts.refId.slice(0, 8).toUpperCase()}`, R - 90, y, 9, regular, gray);
  y -= 22;
  line(y); y -= 16;

  text("PROVIDER", L, y, 8, bold, teal);
  text("PATIENT", L + W / 2, y, 8, bold, teal);
  y -= 14;

  text(opts.providerName, L, y, 10, bold);
  text(opts.patientName, L + W / 2, y, 10, bold);
  y -= 13;

  text(`${opts.providerCredentials}${opts.providerSpecialty ? ` · ${opts.providerSpecialty}` : ""}`, L, y, 8, regular, gray);
  y -= 24;
  line(y); y -= 16;

  text("DIAGNOSIS", L, y, 8, bold, teal);
  y -= 14;
  for (const dl of wrapText(opts.diagnosis, W, 10, regular)) { text(dl, L, y, 10); y -= 14; }
  y -= 10; line(y); y -= 16;

  if (opts.drugs.length > 0) {
    text("MEDICATIONS PRESCRIBED", L, y, 8, bold, teal);
    y -= 16;
    const cols = [L, L + 180, L + 270, L + 380];
    page.drawRectangle({ x: L, y: y - 4, width: W, height: 16, color: rgb(0.94, 0.97, 0.97) });
    text("Drug", cols[0] + 4, y + 1, 8, bold, gray);
    text("Dosage", cols[1] + 4, y + 1, 8, bold, gray);
    text("Frequency", cols[2] + 4, y + 1, 8, bold, gray);
    text("Duration", cols[3] + 4, y + 1, 8, bold, gray);
    y -= 18;
    for (const d of opts.drugs) {
      text(d.name || "—", cols[0] + 4, y, 9);
      text(d.dosage || "—", cols[1] + 4, y, 9);
      text(d.frequency || "—", cols[2] + 4, y, 9);
      text(d.duration || "—", cols[3] + 4, y, 9);
      y -= 14;
      line(y); y -= 2;
    }
    y -= 12; line(y); y -= 16;
  }

  if (opts.treatment) {
    text("TREATMENT NOTES", L, y, 8, bold, teal);
    y -= 14;
    for (const tl of wrapText(opts.treatment, W, 10, regular)) { text(tl, L, y, 10); y -= 14; }
    y -= 10; line(y); y -= 16;
  }

  if (opts.followUp) {
    text("FOLLOW-UP PLAN", L, y, 8, bold, teal);
    y -= 14;
    for (const fl of wrapText(opts.followUp, W, 10, regular)) { text(fl, L, y, 10); y -= 14; }
    y -= 10; line(y); y -= 16;
  }

  y -= 20;
  text("_________________________________", L, y, 10, regular, gray);
  y -= 14;
  text("Provider Signature", L, y, 8, regular, gray);
  y -= 12;
  text(opts.providerName, L, y, 9, bold);

  text("This prescription was generated by StreetdocMD · streetdocmd.com", L, 30, 7, regular, gray);
  line(42);

  return doc.save();
}

function wrapText(str: string, maxWidth: number, fontSize: number, font: PDFFont): string[] {
  const words = str.split(" ");
  const lines: string[] = [];
  let current = "";
  for (const word of words) {
    const test = current ? `${current} ${word}` : word;
    if (font.widthOfTextAtSize(test, fontSize) > maxWidth && current) {
      lines.push(current);
      current = word;
    } else {
      current = test;
    }
  }
  if (current) lines.push(current);
  return lines;
}
