import { PDFDocument, type PDFFont, StandardFonts, rgb } from "pdf-lib";

export interface ReferralPDFOpts {
  refId: string;
  date: string;
  providerName: string;
  providerCredentials: string;
  providerSpecialty: string;
  patientName: string;
  patientAge: string;
  hospitalName: string;
  hospitalAddress: string;
  urgency: "routine" | "urgent" | "emergency";
  reason: string;
  clinicalSummary: string;
  diagnoses: string;
}

export async function buildReferralPDF(opts: ReferralPDFOpts): Promise<Uint8Array> {
  const doc = await PDFDocument.create();
  const page = doc.addPage([595.28, 841.89]);
  const { width, height } = page.getSize();

  const regular = await doc.embedFont(StandardFonts.Helvetica);
  const bold    = await doc.embedFont(StandardFonts.HelveticaBold);

  const black  = rgb(0.05, 0.05, 0.05);
  const gray   = rgb(0.45, 0.45, 0.45);
  const teal   = rgb(0.05, 0.45, 0.45);
  const border = rgb(0.85, 0.85, 0.85);
  const red    = rgb(0.8, 0.1, 0.1);

  const urgencyColors: Record<string, ReturnType<typeof rgb>> = {
    routine:   rgb(0.1, 0.55, 0.3),
    urgent:    rgb(0.8, 0.5, 0.0),
    emergency: red,
  };
  const urgencyLabel = opts.urgency.toUpperCase();
  const urgencyColor = urgencyColors[opts.urgency] ?? teal;

  let y = height - 48;
  const L = 50;
  const R = width - 50;
  const W = R - L;

  function line(yPos: number) {
    page.drawLine({ start: { x: L, y: yPos }, end: { x: R, y: yPos }, thickness: 0.5, color: border });
  }

  function text(s: string, x: number, yPos: number, size: number, font = regular, color = black) {
    page.drawText(s, { x, y: yPos, size, font, color });
  }

  function textBlock(s: string, x: number, startY: number, size: number, maxW: number): number {
    let curY = startY;
    for (const l of wrapText(s, maxW, size, regular)) {
      text(l, x, curY, size);
      curY -= size + 4;
    }
    return curY;
  }

  // Header
  page.drawRectangle({ x: L, y: y - 4, width: W, height: 36, color: teal });
  text("STREETDOCMD", L + 10, y + 10, 16, bold, rgb(1, 1, 1));
  text("Medical Referral Letter", L + 10, y - 2, 9, regular, rgb(0.85, 1, 1));

  // Urgency badge top-right
  const urgLabelW = bold.widthOfTextAtSize(urgencyLabel, 9) + 16;
  page.drawRectangle({ x: R - urgLabelW, y: y - 2, width: urgLabelW, height: 18, color: urgencyColor });
  text(urgencyLabel, R - urgLabelW + 8, y + 4, 9, bold, rgb(1, 1, 1));

  y -= 52;
  text(`Date: ${opts.date}`, L, y, 9, regular, gray);
  text(`Ref: #${opts.refId.slice(0, 8).toUpperCase()}`, R - 110, y, 9, regular, gray);
  y -= 22;
  line(y); y -= 16;

  // From / To
  text("FROM", L, y, 8, bold, teal);
  text("TO", L + W / 2, y, 8, bold, teal);
  y -= 14;
  text(opts.providerName, L, y, 10, bold);
  text(opts.hospitalName, L + W / 2, y, 10, bold);
  y -= 13;
  text(`${opts.providerCredentials}${opts.providerSpecialty ? ` · ${opts.providerSpecialty}` : ""}`, L, y, 8, regular, gray);
  text(opts.hospitalAddress, L + W / 2, y, 8, regular, gray);
  y -= 26;
  line(y); y -= 16;

  // Patient
  text("PATIENT", L, y, 8, bold, teal);
  y -= 14;
  text(`${opts.patientName}, Age ${opts.patientAge}`, L, y, 10, bold);
  y -= 24;
  line(y); y -= 16;

  // Reason for referral
  text("REASON FOR REFERRAL", L, y, 8, bold, teal);
  y -= 14;
  y = textBlock(opts.reason, L, y, 10, W);
  y -= 10; line(y); y -= 16;

  // Diagnoses
  if (opts.diagnoses) {
    text("CURRENT DIAGNOSIS", L, y, 8, bold, teal);
    y -= 14;
    y = textBlock(opts.diagnoses, L, y, 10, W);
    y -= 10; line(y); y -= 16;
  }

  // Clinical summary
  if (opts.clinicalSummary) {
    text("CLINICAL SUMMARY", L, y, 8, bold, teal);
    y -= 14;
    y = textBlock(opts.clinicalSummary, L, y, 10, W);
    y -= 10; line(y); y -= 16;
  }

  // Urgency note
  if (opts.urgency === "emergency") {
    page.drawRectangle({ x: L, y: y - 18, width: W, height: 24, color: rgb(1, 0.94, 0.94) });
    text("EMERGENCY: Immediate attention required. Please see this patient as soon as possible.", L + 8, y - 8, 9, bold, red);
    y -= 30;
  }

  // Signature
  y -= 20;
  text("_________________________________", L, y, 10, regular, gray);
  y -= 14;
  text("Provider Signature & Stamp", L, y, 8, regular, gray);
  y -= 12;
  text(opts.providerName, L, y, 9, bold);

  text("This referral was generated by StreetdocMD · streetdocmd.com", L, 30, 7, regular, gray);
  line(42);

  return doc.save();
}

function wrapText(str: string, maxWidth: number, fontSize: number, font: PDFFont): string[] {
  const words = str.split(" ");
  const lines: string[] = [];
  let current = "";
  for (const word of words) {
    const test = current ? `${current} ${word}` : word;
    if (font.widthOfTextAtSize(test, fontSize) > maxWidth && current) {
      lines.push(current);
      current = word;
    } else {
      current = test;
    }
  }
  if (current) lines.push(current);
  return lines;
}
